const signlangMapping = {
  a: "https://i.ibb.co/S53Dmjx/A.jpg",
  b: "https://i.ibb.co/MRD3GZs/B.jpg",
  c: "https://i.ibb.co/NCtfV93/C.jpg",
  d: "https://i.ibb.co/dG743HX/D.jpg",
  e: "https://i.ibb.co/dWc7075/E.jpg",
  f: "https://i.ibb.co/0Jgv250/F.jpg",
  g: "https://i.ibb.co/mBcK1vQ/G.jpg",
  h: "https://i.ibb.co/ftPgGkw/H.jpg",
  i: "https://i.ibb.co/Fb6fvF2/I.jpg",
  j: "https://i.ibb.co/qgdLR4p/J.jpg",
  k: "https://i.ibb.co/JjmPy9Z/K.jpg",
  l: "https://i.ibb.co/m6mJkxL/L.jpg",
  m: "https://i.ibb.co/fFzNb42/M.jpg",
  n: "https://i.ibb.co/vPz52z9/N.jpg",
  o: "https://i.ibb.co/3RNPgrX/O.jpg",
  p: "https://i.ibb.co/R9h9dPn/P.jpg",
  q: "https://i.ibb.co/2S41qSB/Q.jpg",
  r: "https://i.ibb.co/sKCSw2f/R.jpg",
  s: "https://i.ibb.co/XsMF27s/S.jpg",
  t: "https://i.ibb.co/3dGZrXX/T.jpg",
  u: "https://i.ibb.co/F0VPP8z/U.jpg",
  v: "https://i.ibb.co/YfVyRzx/V.jpg",
  w: "https://i.ibb.co/sCVfZHQ/W.jpg",
  x: "https://i.ibb.co/bJK73SQ/X.jpg",
  y: "https://i.ibb.co/wyLcFGm/Y.jpg",
  z: "https://i.ibb.co/Z63NfQ6/Z.jpg",
  " ": "https://i.ibb.co/2Ys4sxB/ZSpace.jpg",
};

export default signlangMapping;
